[project]
name = "mcp-arena"
version = "0.1.0"
description = "Elegant MCP-based chat application with Ollama integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.110.0",
    "fastmcp>=2.9.2",
    "uvicorn[standard]>=0.29.0",
    "ollama>=0.4.0",
    "duckduckgo-search>=6.1.0",
    "websockets>=12.0",
    "pydantic>=2.5.0",
    "aiofiles>=23.2.1",
    "python-multipart>=0.0.6",
    "httpx>=0.27.0",
    "python-dateutil>=2.8.2"
]
