[project]
name = "mcp-arena"
version = "1.0.0"
description = "Simple Streamlit chat app with Ollama and function calling"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.46.1",
    "requests>=2.32.4",
    "duckduckgo-search>=6.1.0",
    "httpx>=0.27.0",
]
